#!/usr/bin/env python
"""WP5 — TE enrichment at 5 / 10 / 20 kb TSS windows (reviewer major comment 5).

The reviewer's comment
----------------------
"...sensitivity analyses for key findings (e.g., the IFNA-L1 association, the
SVA-termination association) using alternative window sizes (5 kb and 20 kb) and
alternative percentiles (e.g., 10%)."

This script covers the window half: it recomputes class-level and family-level
enrichment at all three window sizes, using the identical contingency table and
the identical N = 500 permutation background construction at each, and then
measures how concordant the three are.

Why the three windows are comparable
------------------------------------
  * The window sets come from ONE TSS definition. `05a_build_windows.sh` recovers
    it from the published 10 kb file (`TSS = end - 5000`, exact for all 38,704
    intervals) and applies half-widths of 2,500 / 5,000 / 10,000.
  * The observed intersections come from one pipeline, and at 10 kb it reproduces
    the published Table 1 counts exactly (582,540 intersections, class for class).
  * The backgrounds are all N = 500 with the same shuffle/intersect semantics. The
    10 kb background is the retained published one (compacted, D1); the 5 kb and
    20 kb ones were generated by `01_permutations_stream.sh`, which
    `01a_consolidate_counts.py --check-legacy` shows is distributionally equivalent
    to the legacy pipeline (largest standardised mean difference 0.16 legacy SD).
  * `N_TSS`, the base-pair span in the contingency table, scales with the window:
    it is recomputed per window from the merged interval span rather than reused
    from the published 10 kb value, since that value IS the 10 kb span.

Concordance measures (this is what the response letter quotes)
--------------------------------------------------------------
  * Spearman and Pearson correlation of the observed/random OR across windows,
    pairwise, at class and family level
  * a permutation test of that correlation against a label-shuffled null, so
    "concordant" is a measured statement rather than an eyeball judgement
  * Bland-Altman summaries (mean difference and limits of agreement)
  * every significance flip, named

Outputs
    output/window_sensitivity_classes.csv      6 classes x 3 windows
    output/window_sensitivity_families.csv     44 families x 3 windows
    output/window_sensitivity_concordance.csv  pairwise correlations + tests
    output/window_sensitivity_flips.csv        every significance flip, named
    output/window_sensitivity_ntss.json        the per-window bp spans used

Usage
    python revision_G3/05b_window_sensitivity.py
    python revision_G3/05b_window_sensitivity.py --summary   # concordance only
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys

import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.multitest import multipletests

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import revision_lib as rl  # noqa: E402

OUTPUT_DIR = rl.OUTPUT_DIR
WINDOWS = ["5kb", "10kb", "20kb"]
N_GENOME = 3_117_275_501  # frozen TEs_mapped_on_TSS_analysis.ipynb cell 55
SIGNIFICANCE_ALPHA = 0.05
N_CONCORDANCE_PERMUTATIONS = 10_000
RANDOM_SEED = 42


def sh(cmd: str) -> str:
    return subprocess.run(
        cmd, shell=True, check=True, capture_output=True, text=True,
        env=dict(os.environ, LC_ALL="C"),
    ).stdout


def window_bp_span(window: str) -> int:
    """Total base pairs covered by a window set, after merging overlaps.

    Merging matters: 38,704 windows over ~28,700 genes overlap heavily, and the
    contingency table needs the union span, not the sum of widths. At 10 kb this
    is the quantity the published table calls N_TSS.
    """
    path = os.path.join(OUTPUT_DIR, f"windows_{window}.bed")
    out = sh(
        f"sort -k1,1 -k2,2n {shlex.quote(path)} | bedtools merge -i - "
        f"| awk -F'\\t' '{{ s += $3 - $2 }} END {{ print s }}'"
    )
    return int(out.strip())


def counts_by(level: str, window: str) -> dict[str, int]:
    """Observed intersecting elements per class or family for one window."""
    column = 4 if level == "class_name" else 3  # projection is score,sub,fam,class
    path = os.path.join(OUTPUT_DIR, f"observed_TEs_in_windows_{window}.tsv.zst")
    out = sh(
        f"zstd -dc {shlex.quote(path)} "
        f"| awk -F'\\t' '{{ n[${column}]++ }} END {{ for (k in n) print k \"\\t\" n[k] }}'"
    )
    return {
        line.rsplit("\t", 1)[0]: int(line.rsplit("\t", 1)[1])
        for line in out.strip().split("\n") if line
    }


def genome_counts_by(level: str) -> dict[str, int]:
    """Genome-wide element totals per class or family."""
    column = 7 if level == "class_name" else 6
    out = sh(
        f"awk -F'\\t' '{{ n[${column}]++ }} END {{ for (k in n) print k \"\\t\" n[k] }}' "
        f"{shlex.quote(rl.REPEATS_BED)}"
    )
    return {
        line.rsplit("\t", 1)[0]: int(line.rsplit("\t", 1)[1])
        for line in out.strip().split("\n") if line
    }


def enrichment_for_window(level: str, window: str, n_tss: int) -> pd.DataFrame:
    """Observed OR, Fisher p, random OR mean/SD and empirical p for one window.

    Uses the published contingency table and the published empirical-p convention
    (2 x min(q, 1-q), clamped to 2/(N+1)), so the 10 kb row of this table is
    directly comparable with Table 1 / the stored family enrichment CSV.
    """
    genome = genome_counts_by(level)
    observed = counts_by(level, window)
    background = rl.permutation_totals(window=window, by=level)
    wide = background.pivot(index="seed", columns=level, values="n").fillna(0)

    rows = []
    for name in sorted(genome):
        if name not in observed:
            continue
        K = genome[name]
        k = observed[name]
        odds_ratio, fisher_p = stats.fisher_exact(
            [[k, n_tss - k], [K - k, (N_GENOME - n_tss) - (K - k)]],
            alternative="two-sided",
        )

        k_random = (
            wide[name].to_numpy(dtype=float) if name in wide.columns
            else np.zeros(1, dtype=float)
        )
        a, b = k_random, n_tss - k_random
        c, d = K - k_random, (N_GENOME - n_tss) - (K - k_random)
        with np.errstate(divide="ignore", invalid="ignore"):
            random_or = (a * d) / (b * c)
        random_or = random_or[np.isfinite(random_or)]

        if len(random_or):
            q = float((random_or < odds_ratio).mean())
            p_emp = max(2 * min(q, 1 - q), 2 / (len(random_or) + 1))
            mean_r, sd_r = float(random_or.mean()), float(random_or.std(ddof=1))
        else:
            q, p_emp, mean_r, sd_r = np.nan, np.nan, np.nan, np.nan

        rows.append(
            {
                "window": window,
                level: name,
                "observed_tes": k,
                "total_tes": K,
                "observed_or": odds_ratio,
                "fisher_p_raw": fisher_p,
                "random_or_mean": mean_r,
                "random_or_sd": sd_r,
                "random_or_quantile_of_observed": q,
                "or_observed_to_random": odds_ratio / mean_r if mean_r else np.nan,
                "empirical_p_raw": p_emp,
                "n_permutations": len(random_or),
            }
        )

    table = pd.DataFrame(rows)
    table["fisher_p_adjusted"] = multipletests(table["fisher_p_raw"], method="fdr_bh")[1]
    table["empirical_p_adjusted"] = multipletests(
        table["empirical_p_raw"].fillna(1.0), method="fdr_bh"
    )[1]
    table["significant"] = table["fisher_p_adjusted"] < SIGNIFICANCE_ALPHA
    return table


def concordance(table: pd.DataFrame, level: str) -> pd.DataFrame:
    """Pairwise agreement of obs/random OR between windows, with a permutation test."""
    rng = np.random.default_rng(RANDOM_SEED)
    wide = table.pivot(index=level, columns="window", values="or_observed_to_random")
    rows = []
    for i, w1 in enumerate(WINDOWS):
        for w2 in WINDOWS[i + 1:]:
            if w1 not in wide.columns or w2 not in wide.columns:
                continue
            pair = wide[[w1, w2]].dropna()
            x, y = pair[w1].to_numpy(), pair[w2].to_numpy()
            if len(x) < 3:
                continue
            rho, rho_p = stats.spearmanr(x, y)
            r, r_p = stats.pearsonr(x, y)

            # Permutation test: how often does a label-shuffled pairing reach this rho?
            null = np.array([
                stats.spearmanr(x, rng.permutation(y)).statistic
                for _ in range(N_CONCORDANCE_PERMUTATIONS)
            ])
            perm_p = (int((null >= rho).sum()) + 1) / (N_CONCORDANCE_PERMUTATIONS + 1)

            diff = y - x
            rows.append(
                {
                    "level": level,
                    "window_a": w1,
                    "window_b": w2,
                    "n": len(x),
                    "spearman_rho": rho,
                    "spearman_p": rho_p,
                    "pearson_r": r,
                    "pearson_p": r_p,
                    "concordance_permutation_p": perm_p,
                    "bland_altman_mean_diff": float(diff.mean()),
                    "bland_altman_sd_diff": float(diff.std(ddof=1)),
                    "bland_altman_loa_lower": float(diff.mean() - 1.96 * diff.std(ddof=1)),
                    "bland_altman_loa_upper": float(diff.mean() + 1.96 * diff.std(ddof=1)),
                }
            )
    return pd.DataFrame(rows)


def significance_flips(table: pd.DataFrame, level: str) -> pd.DataFrame:
    """Every group whose significance call is not the same at all three windows."""
    wide = table.pivot(index=level, columns="window", values="significant")
    present = [w for w in WINDOWS if w in wide.columns]
    flipped = wide[wide[present].nunique(axis=1) > 1]
    if flipped.empty:
        return pd.DataFrame(columns=["level", level] + present)
    out = flipped.reset_index()
    out.insert(0, "level", level)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--summary", action="store_true",
                        help="print concordance from existing outputs and exit")
    args = parser.parse_args()

    if args.summary:
        path = os.path.join(OUTPUT_DIR, "window_sensitivity_concordance.csv")
        if not os.path.exists(path):
            print("Run without --summary first.", file=sys.stderr)
            return 1
        conc = pd.read_csv(path)
        print(conc.to_string(index=False, float_format=lambda v: f"{v:.4g}"))
        worst = conc.spearman_rho.min()
        print(f"\nLowest Spearman rho across all window pairs and levels: {worst:.3f}")
        print("Expectation from the plan was >= 0.9; "
              f"{'met' if worst >= 0.9 else 'NOT met — report as a scale-dependent result'}")
        return 0

    available = [
        w for w in WINDOWS
        if len(os.listdir(rl.permutation_store_dir(w))) >= 500
    ]
    missing = [w for w in WINDOWS if w not in available]
    if missing:
        print(f"WARNING: no complete N=500 background for {missing}; "
              f"proceeding with {available}", file=sys.stderr)
    if not available:
        print("No complete backgrounds. Run 01_permutations_stream.sh first.",
              file=sys.stderr)
        return 1

    spans = {w: window_bp_span(w) for w in available}
    print("Base pairs covered by each window set (merged union):")
    for w, span in spans.items():
        note = ""
        if w == "10kb":
            note = f"   published N_TSS = 272,233,268 -> {'match' if span == 272_233_268 else 'DIFFERS'}"
        print(f"  {w:5s} {span:>13,} bp{note}")
    with open(os.path.join(OUTPUT_DIR, "window_sensitivity_ntss.json"), "w") as fh:
        json.dump(spans, fh, indent=2)

    for level, label in [("class_name", "classes"), ("family_name", "families")]:
        print(f"\n=== {label} ===")
        tables = [
            enrichment_for_window(level, w, spans[w]) for w in available
        ]
        combined = pd.concat(tables, ignore_index=True)
        combined = combined[combined[level] != ""]  # drop the unnamed family
        combined.to_csv(
            os.path.join(OUTPUT_DIR, f"window_sensitivity_{label}.csv"), index=False
        )

        pivot = combined.pivot(index=level, columns="window",
                               values="or_observed_to_random")
        print("observed/random OR by window:")
        print(pivot.reindex(columns=[w for w in WINDOWS if w in pivot.columns])
              .round(3).to_string())

        conc = concordance(combined, level)
        flips = significance_flips(combined, level)
        print(f"\nconcordance ({label}):")
        print(conc[["window_a", "window_b", "n", "spearman_rho", "pearson_r",
                    "concordance_permutation_p", "bland_altman_mean_diff"]]
              .to_string(index=False, float_format=lambda v: f"{v:.4g}"))
        print(f"significance flips: {len(flips)}")
        if not flips.empty:
            print(flips.to_string(index=False))

        mode = "w" if level == "class_name" else "a"
        header = level == "class_name"
        conc.to_csv(os.path.join(OUTPUT_DIR, "window_sensitivity_concordance.csv"),
                    mode=mode, header=header, index=False)
        flips.to_csv(os.path.join(OUTPUT_DIR, "window_sensitivity_flips.csv"),
                     mode=mode, header=header, index=False)

    print("\nWrote window_sensitivity_{classes,families,concordance,flips}.csv "
          "and window_sensitivity_ntss.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
